packages:
  - 'packages/*'
allowBuilds:
  '@swc/core': true
  esbuild: true
  simple-git-hooks: true
  unrs-resolver: true

onlyBuiltDependencies:
  - '@swc/core'
  - 'esbuild'
  - 'simple-git-hooks'
  - 'unrs-resolver'
