export enum AppErrorCode {
  CACHE_KEY_NOT_FOUND = 'CACHE_KEY_NOT_FOUND',
  HTTP_ERROR = 'HTTP_ERROR',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  NOT_FOUND = 'NOT_FOUND',

  POST_NOT_FOUND = 'POST_NOT_FOUND',
  VALIDATION_FAILED = 'VALIDATION_FAILED',
}
